steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tmrw-prd-agent', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tmrw-prd-agent']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tmrw-prd-agent'
      - '--image=gcr.io/$PROJECT_ID/tmrw-prd-agent'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated' 