steps:
  # Build the React frontend
  - name: 'node:18'
    dir: 'product-manager-ai'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:18'
    dir: 'product-manager-ai'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Copy the frontend build into backend/build (fix: copy contents, not directory)
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp -r product-manager-ai/build/. backend/build/

  # Install backend dependencies
  - name: 'node:18'
    dir: 'backend'
    entrypoint: 'npm'
    args: ['install']

  # Deploy to Cloud Run using buildpacks
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'tmrw-prd-agent',
        '--source=backend',
        '--region=us-central1',
        '--platform=managed',
        '--allow-unauthenticated',
        '--port=8080',
        '--set-env-vars=GCLOUD_PROJECT_ID=gen-lang-client-0723709535,GCLOUD_LOCATION=us-central1,GEMINI_MODEL=gemini-2.5-flash,VERTEX_RAG_CORPUS=projects/gen-lang-client-0723709535/locations/us-central1/ragCorpora/2305843009213693952,VERTEX_RAG_ENGINE=projects/gen-lang-client-0723709535/locations/us-central1/ragEngines/2305843009213693952'
      ]
options:
  logging: CLOUD_LOGGING_ONLY 