steps:
  # Build the React frontend
  - name: 'node:18'
    dir: 'product-manager-ai'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:18'
    dir: 'product-manager-ai'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Copy the frontend build to the backend/public directory
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p backend/public
        cp -r product-manager-ai/build/* backend/public/

  # Install backend dependencies
  - name: 'node:18'
    dir: 'backend'
    entrypoint: 'npm'
    args: ['install']

  # Deploy to Cloud Run using buildpacks
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'tmrw-prd-agent',
        '--source=backend',
        '--region=us-central1',
        '--platform=managed',
        '--allow-unauthenticated'
      ]
options:
  logging: CLOUD_LOGGING_ONLY 